# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directories: 
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Api
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Api.Exceptions
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Api.Extensions
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Api.Interfaces
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Api.Models
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Exceptions
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Extensions
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Interfaces
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Models
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Models.Interfaces
      - /IFS_DEV/IFS_SRC/ToennVaot.Components.Core/ToennVaot.Components.Core.Security
    schedule:
      interval: "weekly"
